name: ShellAtolConsole Issue
description: Report a bug or request a feature
title: "[ShellAtolConsole]"
labels:

* shellatolconsole

body:

* type: input
  id: summary
  attributes:
  label: Summary
  validations:
  required: true

* type: textarea
  id: details
  attributes:
  label: Details
  placeholder: |
  Describe your issue here
  validations:
  required: true
