name: ShellAtolConsole Issue
description: Report a bug or request a feature
title: "[ShellAtolConsole]"
labels:
  - shellatolconsole

body:
  - type: input
    id: summary
    attributes:
      label: Summary
    validations:
      required: true

      - type: textarea
    id: body
    attributes:
      label: Body
    validations:
      required: true
